default: &default
 adapter: mysql2
 database: page_index_spider
 pool: 5
 timeout: 5000
 encoding: utf8mb4
 host:  localhost
 port : 3306

development:
 <<: *default
 username: root
 password: abcd1234

production:
 <<: *default
 username: root
 password: abcd1234
